defmodule Mix.Tasks.Legacy.ImportTrips do
  @shortdoc "Imports converted legacy trip bundles into the new app"

  @moduledoc """
  Imports trip bundles generated by `scripts/convert_legacy_csv_for_import.py`.

  ## Usage

      mix legacy.import_trips --bundle-dir prod_backup/import_ready --user-map-file path/to/user_map.json

  ## Options

    * `--bundle-dir` - Directory with `trips.jsonl` (default: `prod_backup/import_ready`)
    * `--user-map-file` - JSON mapping of legacy user ids to target users (required)
    * `--limit` - Import only first N trip bundles
    * `--skip-missing-cities` - Skip destinations/transfers whose geonames city is not found
    * `--continue-on-error` - Continue processing next trips when a trip import fails

  `--user-map-file` expects JSON like:

      {
        "191": "author@example.com",
        "192": "participant@example.com"
      }

  Values may be user emails or user UUID ids in the current environment.

  ## Important

  This task deletes existing trip-related planning data before importing,
  so every run starts from a clean state.
  """

  use Mix.Task

  alias HamsterTravel.LegacyImport.TripsImporter

  @switches [
    bundle_dir: :string,
    user_map_file: :string,
    limit: :integer,
    skip_missing_cities: :boolean,
    continue_on_error: :boolean
  ]

  @impl true
  def run(args) do
    Mix.Task.run("app.start")

    {opts, _argv, invalid} = OptionParser.parse(args, strict: @switches)

    if invalid != [] do
      Mix.raise("Invalid options: #{inspect(invalid)}")
    end

    bundle_dir = Keyword.get(opts, :bundle_dir, "prod_backup/import_ready")
    user_map_file = Keyword.get(opts, :user_map_file)

    if is_nil(user_map_file) do
      Mix.raise("--user-map-file is required")
    end

    import_opts = [
      bundle_dir: bundle_dir,
      user_map_file: user_map_file,
      limit: Keyword.get(opts, :limit),
      skip_missing_cities: Keyword.get(opts, :skip_missing_cities, false),
      continue_on_error: Keyword.get(opts, :continue_on_error, false)
    ]

    case TripsImporter.import(import_opts) do
      {:ok, result} ->
        Mix.shell().info("Legacy import completed")
        Mix.shell().info("  total: #{result.total}")
        Mix.shell().info("  imported: #{result.imported}")
        Mix.shell().info("  failed: #{result.failed}")

        if result.failures != [] do
          Mix.shell().error("Failures:")

          Enum.each(result.failures, fn failure ->
            Mix.shell().error("  #{failure.trip_ref}: #{failure.reason}")
          end)
        end

      {:error, reason} ->
        Mix.raise("Legacy import failed: #{reason}")
    end
  end
end
