defmodule Mix.Tasks.Legacy.ImportTripCovers do
  @shortdoc "Imports legacy trip cover images into current trip cover storage"

  @moduledoc """
  Imports legacy trip covers for already imported trips.

  Covers are loaded from `trips.jsonl` generated by
  `scripts/convert_legacy_csv_for_import.py` (`legacy_cover_url` / `legacy_image_uid` fields),
  downloaded from legacy public CloudFront URLs, and then stored via
  `Planning.update_trip_cover/2` so new cover versions are generated consistently.

  ## Usage

      mix legacy.import_trip_covers --bundle-dir prod_backup/import_ready --user-map-file path/to/user_map.json

  ## Options

    * `--bundle-dir` - Directory with `trips.jsonl` (default: `prod_backup/import_ready`)
    * `--user-map-file` - JSON mapping of legacy user ids to target users (required)
    * `--limit` - Process only first N bundles
    * `--overwrite` - Replace already existing covers
    * `--continue-on-error` - Continue when a trip cover import fails
    * `--dry-run` - Resolve and download checks without writing covers
    * `--cover-base-url` - Base URL used when only `legacy_image_uid` is present
    * `--request-timeout-ms` - HTTP timeout per cover download (default: `120000`)
    * `--report-file` - JSON report output path (default: `prod_backup/import_ready/cover_import_report.json`)
  """

  use Mix.Task

  alias HamsterTravel.LegacyImport.TripCoversImporter

  @switches [
    bundle_dir: :string,
    user_map_file: :string,
    limit: :integer,
    overwrite: :boolean,
    continue_on_error: :boolean,
    dry_run: :boolean,
    cover_base_url: :string,
    request_timeout_ms: :integer,
    report_file: :string
  ]

  @impl true
  def run(args) do
    ensure_cover_import_repo_timeouts()
    Mix.Task.run("app.start")

    {opts, _argv, invalid} = OptionParser.parse(args, strict: @switches)

    if invalid != [] do
      Mix.raise("Invalid options: #{inspect(invalid)}")
    end

    bundle_dir = Keyword.get(opts, :bundle_dir, "prod_backup/import_ready")
    user_map_file = Keyword.get(opts, :user_map_file)

    if is_nil(user_map_file) do
      Mix.raise("--user-map-file is required")
    end

    import_opts = [
      bundle_dir: bundle_dir,
      user_map_file: user_map_file,
      limit: Keyword.get(opts, :limit),
      overwrite: Keyword.get(opts, :overwrite, false),
      continue_on_error: Keyword.get(opts, :continue_on_error, false),
      dry_run: Keyword.get(opts, :dry_run, false),
      cover_base_url: Keyword.get(opts, :cover_base_url),
      request_timeout_ms: Keyword.get(opts, :request_timeout_ms, 120_000),
      report_file:
        Keyword.get(opts, :report_file, "prod_backup/import_ready/cover_import_report.json")
    ]

    case TripCoversImporter.import(import_opts) do
      {:ok, result} ->
        Mix.shell().info("Legacy cover import completed")
        Mix.shell().info("  total: #{result.total}")
        Mix.shell().info("  with_cover: #{result.with_cover}")
        Mix.shell().info("  updated: #{result.updated}")
        Mix.shell().info("  skipped_no_cover: #{result.skipped_no_cover}")
        Mix.shell().info("  skipped_existing_cover: #{result.skipped_existing_cover}")
        Mix.shell().info("  skipped_no_trip_match: #{result.skipped_no_trip_match}")
        Mix.shell().info("  failed: #{result.failed}")

        if result.failures != [] do
          Mix.shell().error("Failures:")

          Enum.each(result.failures, fn failure ->
            Mix.shell().error("  #{failure.trip_ref}: #{failure.reason}")
          end)
        end

      {:error, reason} ->
        Mix.raise("Legacy cover import failed: #{reason}")
    end
  end

  # Same rationale as trip import task: proxied production DB and image processing
  # can exceed default checkout/query timeout values.
  defp ensure_cover_import_repo_timeouts do
    System.put_env(
      "LEGACY_IMPORT_DB_TIMEOUT_MS",
      System.get_env("LEGACY_IMPORT_DB_TIMEOUT_MS") || "600000"
    )

    System.put_env(
      "LEGACY_IMPORT_DB_POOL_TIMEOUT_MS",
      System.get_env("LEGACY_IMPORT_DB_POOL_TIMEOUT_MS") || "600000"
    )
  end
end
