service: hamster-travel
image: <%= ENV.fetch("KAMAL_REGISTRY_USERNAME", "anmarchenko") %>/hamster-travel

<% registry_server = ENV.fetch("KAMAL_REGISTRY_SERVER", "127.0.0.1:5555") %>

require_destination: true
minimum_version: 2.12.0
retain_containers: 3
deploy_timeout: 60
readiness_delay: 10

registry:
  server: <%= registry_server %>
<% if registry_server.start_with?("127.0.0.1:") %>
  username: local
  password: local
<% else %>
  username: <%= ENV.fetch("KAMAL_REGISTRY_USERNAME", "anmarchenko") %>
  password:
    - KAMAL_REGISTRY_PASSWORD
<% end %>

builder:
  arch: amd64
  context: .
  driver: docker

aliases:
  logs: app logs --roles web --follow
  migrate: app exec --primary --reuse "/app/bin/migrate"
  shell: app exec --primary --interactive --reuse "/bin/sh"
  verify-storage: app exec --primary --reuse "/app/bin/hamster_travel eval HamsterTravel.Release.verify_waffle_storage"
