defmodule HamsterTravel.LegacyImport.TripsImporter do
  @moduledoc """
  Imports converted legacy trip bundles into the new planning schema.

  Input is expected to be generated by `scripts/convert_legacy_csv_for_import.py`.
  """

  import Ecto.Query, warn: false

  alias HamsterTravel.Accounts
  alias HamsterTravel.Accounts.User
  alias HamsterTravel.Geo.City
  alias HamsterTravel.Planning

  alias HamsterTravel.Planning.{
    Accommodation,
    Activity,
    DayExpense,
    Destination,
    Expense,
    FoodExpense,
    Note,
    Transfer,
    Trip,
    TripParticipant,
    TripTombstone
  }

  alias HamsterTravel.Repo
  require Logger

  @type import_opts :: [
          bundle_dir: String.t(),
          user_map_file: String.t(),
          limit: non_neg_integer() | nil,
          skip_missing_cities: boolean(),
          continue_on_error: boolean(),
          purge_existing: boolean()
        ]

  @type import_result :: %{
          imported: non_neg_integer(),
          failed: non_neg_integer(),
          total: non_neg_integer(),
          failures: list(%{trip_ref: String.t() | nil, reason: String.t()})
        }

  @spec import(import_opts()) :: {:ok, import_result()} | {:error, String.t()}
  def import(opts) do
    with {:ok, bundle_dir} <- fetch_required_path(opts, :bundle_dir),
         {:ok, user_map_file} <- fetch_required_path(opts, :user_map_file),
         {:ok, bundles} <- load_trip_bundles(bundle_dir, opts[:limit]),
         {:ok, legacy_user_ids} <- collect_legacy_user_ids(bundles),
         {:ok, legacy_user_map} <- load_user_map(user_map_file),
         {:ok, resolved_users} <- resolve_users(legacy_user_ids, legacy_user_map),
         {:ok, city_id_by_geonames} <- preload_cities_by_geonames_id(bundles),
         :ok <- maybe_purge_existing_trips_data(Keyword.get(opts, :purge_existing, true)) do
      do_import(
        bundles,
        resolved_users,
        city_id_by_geonames,
        skip_missing_cities: Keyword.get(opts, :skip_missing_cities, false),
        continue_on_error: Keyword.get(opts, :continue_on_error, false)
      )
    end
  end

  defp maybe_purge_existing_trips_data(false), do: :ok
  defp maybe_purge_existing_trips_data(true), do: purge_existing_trips_data()

  defp fetch_required_path(opts, key) do
    case Keyword.get(opts, key) do
      nil ->
        {:error, "missing option #{key}"}

      path when is_binary(path) ->
        {:ok, Path.expand(path)}
    end
  end

  defp load_trip_bundles(bundle_dir, limit) do
    path = Path.join(bundle_dir, "trips.jsonl")

    if File.exists?(path) do
      bundles =
        path
        |> File.stream!()
        |> Stream.reject(&String.match?(&1, ~r/^\s*$/u))
        |> Stream.map(&Jason.decode!/1)
        |> maybe_take(limit)
        |> Enum.to_list()

      {:ok, bundles}
    else
      {:error, "trips.jsonl not found at #{path}"}
    end
  end

  defp maybe_take(stream, nil), do: stream

  defp maybe_take(stream, limit) when is_integer(limit) and limit >= 0,
    do: Stream.take(stream, limit)

  defp collect_legacy_user_ids(bundles) do
    legacy_user_ids =
      bundles
      |> Enum.flat_map(fn bundle ->
        author = bundle["author_legacy_user_id"]
        participants = bundle["participant_legacy_user_ids"] || []
        [author | participants]
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq()
      |> Enum.sort()

    {:ok, legacy_user_ids}
  end

  defp load_user_map(path) do
    with {:ok, body} <- File.read(path),
         {:ok, parsed} <- Jason.decode(body) do
      {:ok, parsed}
    else
      {:error, :enoent} ->
        {:error, "user map file not found: #{path}"}

      {:error, reason} ->
        {:error, "failed to read user map file #{path}: #{inspect(reason)}"}
    end
  end

  defp resolve_users(legacy_user_ids, legacy_user_map) do
    resolved =
      Enum.reduce_while(legacy_user_ids, {:ok, %{}}, fn legacy_id, {:ok, acc} ->
        key = to_string(legacy_id)

        case Map.fetch(legacy_user_map, key) do
          :error ->
            {:halt, {:error, "missing user mapping for legacy user #{key}"}}

          {:ok, nil} ->
            {:halt, {:error, "mapping for legacy user #{key} is null"}}

          {:ok, mapped} ->
            case find_user_by_mapping_value(mapped) do
              {:ok, %User{} = user} ->
                {:cont, {:ok, Map.put(acc, legacy_id, user)}}

              {:error, reason} ->
                {:halt, {:error, "cannot resolve mapped user for legacy #{key}: #{reason}"}}
            end
        end
      end)

    resolved
  end

  defp find_user_by_mapping_value(value) when is_binary(value) do
    normalized = value

    cond do
      normalized == "" ->
        {:error, "empty mapping value"}

      String.contains?(normalized, "@") ->
        case Accounts.get_user_by_email(normalized) do
          %User{} = user -> {:ok, user}
          nil -> {:error, "email not found: #{normalized}"}
        end

      true ->
        case Repo.get(User, normalized) do
          %User{} = user -> {:ok, user}
          nil -> {:error, "user id not found: #{normalized}"}
        end
    end
  end

  defp find_user_by_mapping_value(value) do
    value
    |> to_string()
    |> find_user_by_mapping_value()
  end

  defp preload_cities_by_geonames_id(bundles) do
    geonames_ids =
      bundles
      |> Enum.flat_map(fn bundle ->
        destination_geo_ids =
          bundle
          |> Map.get("destinations", [])
          |> Enum.map(&blank_to_nil(&1["city_geonames_id"]))

        transfer_geo_ids =
          bundle
          |> Map.get("transfers", [])
          |> Enum.flat_map(fn transfer ->
            [
              blank_to_nil(transfer["departure_city_geonames_id"]),
              blank_to_nil(transfer["arrival_city_geonames_id"])
            ]
          end)

        destination_geo_ids ++ transfer_geo_ids
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq()

    city_id_by_geonames =
      from(c in City, where: c.geonames_id in ^geonames_ids, select: {c.geonames_id, c.id})
      |> Repo.all()
      |> Map.new()

    {:ok, city_id_by_geonames}
  end

  defp purge_existing_trips_data do
    case Repo.transaction(fn ->
           deleted_expenses = Repo.delete_all(Expense) |> elem(0)
           deleted_trip_participants = Repo.delete_all(TripParticipant) |> elem(0)
           deleted_notes = Repo.delete_all(Note) |> elem(0)
           deleted_transfers = Repo.delete_all(Transfer) |> elem(0)
           deleted_activities = Repo.delete_all(Activity) |> elem(0)
           deleted_day_expenses = Repo.delete_all(DayExpense) |> elem(0)
           deleted_food_expenses = Repo.delete_all(FoodExpense) |> elem(0)
           deleted_accommodations = Repo.delete_all(Accommodation) |> elem(0)
           deleted_destinations = Repo.delete_all(Destination) |> elem(0)
           deleted_trips = Repo.delete_all(Trip) |> elem(0)
           deleted_tombstones = Repo.delete_all(TripTombstone) |> elem(0)

           %{
             expenses: deleted_expenses,
             trip_participants: deleted_trip_participants,
             notes: deleted_notes,
             transfers: deleted_transfers,
             activities: deleted_activities,
             day_expenses: deleted_day_expenses,
             food_expenses: deleted_food_expenses,
             accommodations: deleted_accommodations,
             destinations: deleted_destinations,
             trips: deleted_trips,
             trip_tombstones: deleted_tombstones
           }
         end) do
      {:ok, deleted} ->
        Logger.info("Purged existing trip data before import: #{inspect(deleted)}")
        :ok

      {:error, reason} ->
        {:error, "failed to purge existing trips data: #{format_error(reason)}"}
    end
  end

  defp do_import(bundles, resolved_users, city_id_by_geonames, opts) do
    continue_on_error = Keyword.get(opts, :continue_on_error, false)
    skip_missing_cities = Keyword.get(opts, :skip_missing_cities, false)

    initial = %{imported: 0, failed: 0, total: length(bundles), failures: []}

    result =
      Enum.reduce_while(bundles, initial, fn bundle, acc ->
        case import_bundle(bundle, resolved_users, city_id_by_geonames, skip_missing_cities) do
          {:ok, _trip} ->
            {:cont, %{acc | imported: acc.imported + 1}}

          {:error, reason} ->
            trip_ref = bundle["trip_ref"]
            failure = %{trip_ref: trip_ref, reason: reason}
            updated = %{acc | failed: acc.failed + 1, failures: [failure | acc.failures]}

            if continue_on_error do
              Logger.error("Legacy import failed for #{trip_ref}: #{reason}")
              {:cont, updated}
            else
              {:halt, updated}
            end
        end
      end)

    {:ok, %{result | failures: Enum.reverse(result.failures)}}
  end

  defp import_bundle(bundle, resolved_users, city_id_by_geonames, skip_missing_cities) do
    case Repo.transaction(fn ->
           with {:ok, author} <- fetch_author(bundle, resolved_users),
                {:ok, trip} <- create_trip(bundle, author),
                :ok <- create_participants(trip, bundle, author, resolved_users),
                :ok <- create_destinations(trip, bundle, city_id_by_geonames, skip_missing_cities),
                :ok <- create_accommodations(trip, bundle),
                :ok <- create_transfers(trip, bundle, city_id_by_geonames, skip_missing_cities),
                :ok <- create_activities(trip, bundle),
                :ok <- create_day_expenses(trip, bundle),
                :ok <- create_notes(trip, bundle),
                :ok <- update_food_expense(trip, bundle) do
             trip
           else
             {:error, reason} -> Repo.rollback(reason)
           end
         end) do
      {:ok, %Trip{} = trip} -> {:ok, trip}
      {:error, reason} -> {:error, format_error(reason)}
    end
  rescue
    error in [Postgrex.Error, DBConnection.ConnectionError] ->
      {:error, Exception.message(error)}
  end

  defp fetch_author(bundle, resolved_users) do
    author_legacy_id = bundle["author_legacy_user_id"]

    case Map.get(resolved_users, author_legacy_id) do
      %User{} = user -> {:ok, user}
      nil -> {:error, "missing resolved author for legacy user #{author_legacy_id}"}
    end
  end

  defp create_trip(bundle, %User{} = author) do
    attrs =
      %{
        "name" => truncate_string(bundle["name"], 255),
        "status" => bundle["status"],
        "dates_unknown" => bundle["dates_unknown"],
        "duration" => bundle["duration"],
        "start_date" => bundle["start_date"],
        "end_date" => bundle["end_date"],
        "currency" => bundle["currency"],
        "people_count" => bundle["people_count"],
        "private" => bundle["private"]
      }
      |> drop_nil_values()

    case Planning.create_trip(attrs, author) do
      {:ok, %Trip{} = trip} ->
        {:ok, trip}

      {:error, changeset} ->
        {:error, {:create_trip_failed, changeset}}
    end
  end

  defp create_participants(trip, bundle, author, resolved_users) do
    participants = bundle["participant_legacy_user_ids"] || []

    Enum.reduce_while(participants, :ok, fn legacy_user_id, :ok ->
      case Map.get(resolved_users, legacy_user_id) do
        nil ->
          {:halt, {:error, "missing resolved participant for legacy user #{legacy_user_id}"}}

        %User{id: user_id} when user_id == author.id ->
          {:cont, :ok}

        %User{id: user_id} ->
          changeset =
            TripParticipant.changeset(%TripParticipant{}, %{trip_id: trip.id, user_id: user_id})

          case Repo.insert(changeset,
                 on_conflict: :nothing,
                 conflict_target: [:trip_id, :user_id]
               ) do
            {:ok, _} -> {:cont, :ok}
            {:error, cs} -> {:halt, {:error, {:create_participant_failed, cs}}}
          end
      end
    end)
  end

  defp create_destinations(trip, bundle, city_id_by_geonames, skip_missing_cities) do
    destinations = bundle["destinations"] || []

    Enum.reduce_while(destinations, :ok, fn destination, :ok ->
      geonames_id = blank_to_nil(destination["city_geonames_id"])

      case Map.get(city_id_by_geonames, geonames_id) do
        nil when skip_missing_cities ->
          Logger.warning(
            "Skipping destination for trip #{trip.id}: city geonames #{inspect(geonames_id)} not found"
          )

          {:cont, :ok}

        nil ->
          {:halt, {:error, "destination city geonames not found: #{inspect(geonames_id)}"}}

        city_id ->
          attrs =
            %{
              "city_id" => city_id,
              "start_day" => destination["start_day"],
              "end_day" => destination["end_day"]
            }
            |> drop_nil_values()

          case Planning.create_destination(trip, attrs) do
            {:ok, _destination} -> {:cont, :ok}
            {:error, cs} -> {:halt, {:error, {:create_destination_failed, cs}}}
          end
      end
    end)
  end

  defp create_accommodations(trip, bundle) do
    accommodations = bundle["accommodations"] || []

    Enum.reduce_while(accommodations, :ok, fn accommodation, :ok ->
      attrs =
        %{
          "name" => truncate_string(accommodation["name"], 255),
          "link" => truncate_string(blank_to_nil(accommodation["link"]), 255),
          "address" => truncate_string(blank_to_nil(accommodation["address"]), 255),
          "note" => blank_to_nil(accommodation["note"]),
          "start_day" => accommodation["start_day"],
          "end_day" => accommodation["end_day"]
        }
        |> maybe_put_expense(
          accommodation["expense"],
          accommodation["name"] || "Legacy accommodation expense",
          trip.currency
        )

      case Planning.create_accommodation(trip, attrs) do
        {:ok, _record} -> {:cont, :ok}
        {:error, cs} -> {:halt, {:error, {:create_accommodation_failed, cs}}}
      end
    end)
  end

  defp create_transfers(trip, bundle, city_id_by_geonames, skip_missing_cities) do
    transfers = bundle["transfers"] || []

    Enum.reduce_while(transfers, :ok, fn transfer, :ok ->
      departure_geonames_id = blank_to_nil(transfer["departure_city_geonames_id"])
      arrival_geonames_id = blank_to_nil(transfer["arrival_city_geonames_id"])

      departure_city_id = Map.get(city_id_by_geonames, departure_geonames_id)
      arrival_city_id = Map.get(city_id_by_geonames, arrival_geonames_id)

      if is_nil(departure_city_id) or is_nil(arrival_city_id) do
        if skip_missing_cities do
          Logger.warning(
            "Skipping transfer for trip #{trip.id}: missing city mapping dep=#{inspect(departure_geonames_id)} arr=#{inspect(arrival_geonames_id)}"
          )

          {:cont, :ok}
        else
          {:halt,
           {:error,
            "transfer city geonames not found dep=#{inspect(departure_geonames_id)} arr=#{inspect(arrival_geonames_id)}"}}
        end
      else
        attrs =
          %{
            "transport_mode" => transfer["transport_mode"],
            "departure_time" => transfer["departure_time"],
            "arrival_time" => transfer["arrival_time"],
            "note" => blank_to_nil(transfer["note"]),
            "vessel_number" => truncate_string(blank_to_nil(transfer["vessel_number"]), 255),
            "carrier" => truncate_string(blank_to_nil(transfer["carrier"]), 255),
            "departure_station" =>
              truncate_string(blank_to_nil(transfer["departure_station"]), 255),
            "arrival_station" => truncate_string(blank_to_nil(transfer["arrival_station"]), 255),
            "day_index" => transfer["day_index"],
            "departure_city_id" => departure_city_id,
            "arrival_city_id" => arrival_city_id
          }
          |> maybe_put_expense(
            transfer["expense"],
            "Transfer expense",
            trip.currency
          )

        case Planning.create_transfer(trip, attrs) do
          {:ok, _record} -> {:cont, :ok}
          {:error, cs} -> {:halt, {:error, {:create_transfer_failed, cs}}}
        end
      end
    end)
  end

  defp create_activities(trip, bundle) do
    activities = bundle["activities"] || []

    Enum.reduce_while(activities, :ok, fn activity, :ok ->
      attrs =
        %{
          "name" => truncate_string(activity["name"], 255),
          "day_index" => activity["day_index"],
          "priority" => activity["priority"],
          "link" => truncate_string(blank_to_nil(activity["link"]), 255),
          "address" => truncate_string(blank_to_nil(activity["address"]), 255),
          "description" => blank_to_nil(activity["description"])
        }
        |> maybe_put_expense(
          activity["expense"],
          activity["name"] || "Activity expense",
          trip.currency
        )

      case Planning.create_activity(trip, attrs) do
        {:ok, _record} -> {:cont, :ok}
        {:error, cs} -> {:halt, {:error, {:create_activity_failed, cs}}}
      end
    end)
  end

  defp create_day_expenses(trip, bundle) do
    day_expenses = bundle["day_expenses"] || []

    Enum.reduce_while(day_expenses, :ok, fn day_expense, :ok ->
      attrs =
        %{
          "name" => truncate_string(day_expense["name"], 255),
          "day_index" => day_expense["day_index"]
        }
        |> maybe_put_expense(
          day_expense["expense"],
          day_expense["name"] || "Legacy day expense",
          trip.currency
        )

      case Planning.create_day_expense(trip, attrs) do
        {:ok, _record} -> {:cont, :ok}
        {:error, cs} -> {:halt, {:error, {:create_day_expense_failed, cs}}}
      end
    end)
  end

  defp create_notes(trip, bundle) do
    notes = bundle["notes"] || []

    Enum.reduce_while(notes, :ok, fn note, :ok ->
      attrs =
        %{
          "title" => truncate_string(note["title"], 255),
          "text" => blank_to_nil(note["text"]),
          "day_index" => note["day_index"]
        }
        |> drop_nil_values()

      case Planning.create_note(trip, attrs) do
        {:ok, _record} -> {:cont, :ok}
        {:error, cs} -> {:halt, {:error, {:create_note_failed, cs}}}
      end
    end)
  end

  defp update_food_expense(trip, bundle) do
    case bundle["food_expense"] do
      nil ->
        :ok

      food_expense ->
        reloaded_trip = Planning.get_trip!(trip.id)
        record = reloaded_trip.food_expense

        if record == nil do
          {:error, "trip #{trip.id} is missing default food_expense"}
        else
          attrs =
            %{
              "price_per_day" =>
                money_from_cents(
                  food_expense["price_per_day_cents"],
                  food_expense["expense"]["currency"]
                ),
              "days_count" => food_expense["days_count"],
              "people_count" => food_expense["people_count"]
            }
            |> drop_nil_values()

          case Planning.update_food_expense(record, attrs) do
            {:ok, _updated} -> :ok
            {:error, cs} -> {:error, {:update_food_expense_failed, cs}}
          end
        end
    end
  end

  defp maybe_put_expense(attrs, expense, default_name, currency) do
    expense_attrs =
      case build_expense_attrs(expense) do
        nil -> build_zero_expense_attrs(default_name, currency)
        parsed -> parsed
      end

    Map.put(attrs, "expense", expense_attrs)
  end

  defp build_expense_attrs(expense) do
    cents = expense["amount_cents"]
    currency = blank_to_nil(expense["currency"])

    if is_integer(cents) and cents >= 0 and is_binary(currency) do
      %{
        "name" => truncate_string(blank_to_nil(expense["name"]), 255),
        "price" => money_from_cents(cents, currency)
      }
      |> drop_nil_values()
    else
      nil
    end
  end

  defp money_from_cents(cents, currency) when is_integer(cents) and is_binary(currency) do
    Money.from_integer(cents, currency)
  end

  defp money_from_cents(_cents, _currency), do: nil

  defp build_zero_expense_attrs(default_name, currency) when is_binary(currency) do
    %{
      "name" => truncate_string(blank_to_nil(default_name) || "Legacy expense", 255),
      "price" => money_from_cents(0, currency)
    }
    |> drop_nil_values()
  end

  defp blank_to_nil(nil), do: nil

  defp blank_to_nil(value) when is_binary(value) do
    case value do
      "" -> nil
      raw -> raw
    end
  end

  defp blank_to_nil(value), do: value

  defp drop_nil_values(map) do
    Enum.reduce(map, %{}, fn {key, value}, acc ->
      if is_nil(value), do: acc, else: Map.put(acc, key, value)
    end)
  end

  defp truncate_string(nil, _limit), do: nil

  defp truncate_string(value, _limit) when is_binary(value), do: value

  defp truncate_string(value, _limit), do: value

  defp format_error({tag, %Ecto.Changeset{} = changeset}) do
    "#{tag}: #{inspect(Ecto.Changeset.traverse_errors(changeset, &translate_error/1))}"
  end

  defp format_error(%Ecto.Changeset{} = changeset) do
    inspect(Ecto.Changeset.traverse_errors(changeset, &translate_error/1))
  end

  defp format_error(reason), do: inspect(reason)

  defp translate_error({msg, opts}) do
    Enum.reduce(opts, msg, fn {key, value}, acc ->
      String.replace(acc, "%{#{key}}", to_string(value))
    end)
  end
end
